version: '3.8'
services:

  mongo-db:
    image: mongo:5.0.14
    container_name: sop-mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  app-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fc-api
    ports:
      - "5000:5000"
    environment:
      - IGNORE_ENVIRONMENT=1
      - MONGO_DATABASE=fc-mongo
      - MONGO_URI=mongodb://mongoadmin:secret@sop-mongo:27017/{MONGO_DATABASE}?authSource=admin&authMechanism=SCRAM-SHA-1
      - FRETERAPIDO_API_URL=https://sp.freterapido.com/api/v3/quote/simulate
      - TOKEN=1d52a9b6b78cf07b08586152459a5c90
      - PLATFORMCODE=5AKVkHqCn
      - DISPATCHERSZIPCODE=29161376
      - REGISTEREDNUMBER=25438296000158
    depends_on:
      - mongo-db
