name: Integration Tests

on:
  pull_request:
    branches:
      - main
      - development
      - "release-**"

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Execute Tests
        working-directory: ./
        run: make integration-tests
